# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9034fc92bba158e43979daaa4f8a495b0d875da805906a5d73040cb76de2d0009329bccd58c09eec42d6e7e227d73f8edc2d1f8eed4fa8da121e8ad5c9d0c50

test:
  secret_key_base: 169b161c9b7dca34116bc18731c65e8c30302286fe015b12876e789b6ec82af8380960c6efb3e27f66fd8d89c364e1f6a7ec9501c0beb69bcfb0cf5114d0a75c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
